/*
 * em8300_reg.c
 *
 * Copyright (C) 2000 Henrik Johansson <lhj@users.sourceforge.net>
 *
 *  This program is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU General Public License
 *  as published by the Free Software Foundation; either version 2
 *  of the License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 */

char *ucodereg_names[] = {
	"MV_Command",
	"MV_Status",
	"MV_BuffStart_Lo",
	"MV_BuffStart_Hi",
	"MV_BuffSize_Lo",
	"MV_BuffSize_Hi",
	"MV_RdPtr_Lo",
	"MV_RdPtr_Hi",
	"MV_Threshold",
	"MV_Wrptr_Lo",
	"MV_Wrptr_Hi",
	"MV_PCIRdPtr",
	"MV_PCIWrPtr",
	"MV_PCISize",
	"MV_PCIStart",
	"MV_PTSRdPtr",
	"MV_PTSSize",
	"MV_PTSFifo",
	"MV_SCRSpeed",
	"MV_SCRlo",
	"MV_SCRhi",
	"MV_FrameCntLo",
	"MV_FrameCntHi",
	"MV_FrameEventLo",
	"MV_FrameEventHi",
	"MV_AccSpeed",
	"Width_Buf3",
	"MA_Command",
	"MA_Status",
	"MA_BuffStart_Lo",
	"MA_BuffStart_Hi",
	"MA_BuffSize",
	"MA_BuffSize_Hi",
	"MA_Rdptr",
	"MA_Rdptr_Hi",
	"MA_Threshold",
	"MA_Wrptr",
	"MA_Wrptr_Hi",
	"Q_IrqMask",
	"Q_IrqStatus",
	"Q_IntCnt",
	"MA_PCIRdPtr",
	"MA_PCIWrPtr",
	"MA_PCISize",
	"MA_PCIStart",
	"SP_Command",
	"SP_Status",
	"SP_BuffStart_Lo",
	"SP_BuffStart_Hi",
	"SP_BuffSize_Lo",
	"SP_BuffSize_Hi",
	"SP_RdPtr_Lo",
	"SP_RdPtr_Hi",
	"SP_Wrptr_Lo",
	"SP_Wrptr_Hi",
	"SP_PCIRdPtr",
	"SP_PCIWrPtr",
	"SP_PCISize",
	"SP_PCIStart",
	"SP_PTSRdPtr",
	"SP_PTSSize",
	"SP_PTSFifo",
	"DICOM_DisplayBuffer",
	"Vsync_DBuf",
	"DICOM_TvOut",
	"DICOM_UpdateFlag",
	"DICOM_VSyncLo1",
	"DICOM_VSyncLo2",
	"DICOM_VSyncDelay1",
	"DICOM_VSyncDelay2",
	"DICOM_Display_Data",
	"PicPTSLo",
	"PicPTSHi",
	"Error_Code",
	"DisplayHorSize",
	"Line21Buf1_Cnt",
	"Line21Buf2_Cnt",
	"TimeCodeHi",
	"TimeCodeLo",
	"AUTH_Challenge",
	"AUTH_Response",
	"AUTH_Command",
	"Timer_Cnt",
	"Ovl_Addr",
	"Button_Color",
	"Button_Contrast",
	"Button_Top",
	"Button_Bottom",
	"Button_Left",
	"Button_Right",
	"SP_Palette",
	"DICOM_FrameTop",
	"DICOM_FrameBottom",
	"DICOM_FrameLeft",
	"DICOM_FrameRight",
	"DICOM_VisibleTop",
	"DICOM_VisibleBottom",
	"DICOM_VisibleLeft",
	"DICOM_VisibleRight",
	"DICOM_BCSLuma",
	"DICOM_BCSChroma",
	"DICOM_Control",
	"DICOM_Controlx",
	"MV_CryptKey",
	"DICOM_Kmin",
	"MicroCodeVersion",
	"ForcedLeftParity",
	"L21_Buf1",
	"L21_Buf2",
	"Mute_Pattern",
	"Mute_Patternrityhtm",
	NULL
};
